---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "{% liquid \r\n\r\nassign index = trmnl.system.timestamp_utc | modulo: 3500 | plus: 0\r\nif difficulty == \"insane\"\r\n\r\nassign diff = \"hard\"\r\nelse\r\nassign diff = difficulty\r\nendif\r\n%}\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-word-search-plugin/main/data/{{size}}/{{diff}}/{{index}}.json\r\n\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-word-search-plugin/main/data/8/{{diff}}/{{index}}.json"
polling_headers: ''
polling_body: ''
id: 249847
custom_fields:
- keyname: about
  name: About This Plugin
  field_type: author_bio
  help_text: TRMNL X Ready
  description: Solve <strong>Word Search</strong>es directly on your TRMNL!<br /><br /> Get stuck on a tricky word search puzzle?<br />Simply scan the QR code to reveal the solution!
  github_url: https://github.com/ExcuseMi/trmnl-word-search-plugin
  category: games
- keyname: difficulty
  field_type: select
  name: Difficulty
  description: Select your challenge level
  options:
  - Easy ∙ 2 directions, no backwards words: easy
  - Medium ∙ 4 directions, 10% backwards: medium
  - Hard ∙ 8 directions, 25% backwards: hard
  - Insane ∙ Hard puzzle without word list: insane
  default: medium
  optional: true
- keyname: size
  field_type: select
  name: Size
  description: Smaller grids = easier puzzles. Larger grids = harder puzzles.<br />Small to medium devices will show 8×8 puzzles by default for better readability.
  options:
  - 8X8: '8'
  - 10x10: '10'
  - 12x12: '12'
  - 15x15: '15'
  default: '10'
  optional: true
- keyname: show_solution
  field_type: select
  name: Show solution QR Code
  options:
  - 'Yes': 'yes'
  - 'No': 'no'
  default: 'yes'
  optional: true
name: Word Search (fork)
refresh_interval: 1440
